apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: xplat-stg@fptcloud.com
  password: aMUsE4IZznYlVWHnJiBzlciVnF3LOUQo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: registry-uat.fke.fptcloud.com/576bb055-bc8d-4b31-a36a-a454eaeb2921/test:56
      # - image: nguyenhoangminh1106/test:51
        name: flaskdemo
        resources: {}
      imagePullSecrets:
      - name: registry-credentials
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
