apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: eyAiYXV0aHMiOiB7ICJodHRwczovL3JlZ2lzdHJ5LXVhdC5ma2UuZnB0Y2xvdWQuY29tIjogeyAiYXV0aCI6ICJlSEJzWVhRdGMzUm5RR1p3ZEdOc2IzVmtMbU52YlRwaFRWVnpSVFJKV25wdVdXeFdWMGh1U21sQ2VteGphVlp1UmpOTVQxVlJidz09IiB9IH0gfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: registry-uat.fke.fptcloud.com/576bb055-bc8d-4b31-a36a-a454eaeb2921/test:75
      # - image: nguyenhoangminh1106/test:51
        name: flaskdemo
        resources: {}
        volumeMounts:
          - name: resolve-domain
            mountPath: /etc/hosts
      imagePullSecrets:
      - name: myregistrykey
      volumes:
      - name: resolve-domain
        hostPath:
          path: /etc/hosts
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
